<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.APIGatewayEvents" Version="3.0.0" />
    <PackageReference Include="Amazon.Lambda.Core" Version="3.1.1" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="3.0.0" />
    <PackageReference Include="AWSSDK.SecretsManager" Version="3.7.501.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\packages\Mikepattyn.Email\Mikepattyn.Email\Mikepattyn.Email.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Templates\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
